# 1. build stage
FROM gradle:8.7-jdk21 AS builder
WORKDIR /build

COPY . .

# gradlew 실행 권한
RUN chmod +x gradlew

# Spring Boot jar 빌드 (테스트 제외)
RUN ./gradlew clean bootJar -x test

# 2. runtime stage
FROM eclipse-temurin:21-jre
WORKDIR /app

# jar 복사
COPY --from=builder /build/build/libs/*.jar app.jar

# 포트
EXPOSE 8080

# 실행
ENTRYPOINT ["java", "-jar", "/app/app.jar"]